### ISSUE TITLE
Could I have some 'mask.py' command examples?

### ISSUE THREAD

**Issue by amoudomola** [biomag-lab/hypocotyl-UNet#1]
Hi.
This is a really wonderful tool for plant researchers. I always wanted to have softwares like this.

At the moment, I'm just testing this script with a small number of image files before scaling up, and I have some questions.
I somehow ran the mask script, but not sure the option I typed in was applied or not.
Should I type "True" after the command option for the argument "--make_patches"  in the Step 11?

another question is that for the outlining the images. Would it be better to outline them more precisely (fine outlining of the image borders, or the details of adventitious root in the root-hypocoty junction, etc.) or do that including the backgroud area a little? Without knowing the actuall algorithm behind, I don't know what would improve the segmentation process.

For the training, Do I have to use the sub-folders in the "converted" folder generated by the previous "mask.py" script?
mask.py also generated "patched_images" folder. Do I need this as well?

Thanks a lot.

**Comment by cosmic-cortex** [comment]
Hi!

Thanks, I hope you'll find it useful!

About the `mask.py` script: yes, if you want to slice your images up to patches, just add `--make_patches True`.

Regarding the images: in principle, you shouldn't include the background area, but it is not a problem if you are not 100% precise everywhere. The segmentation is made with the U-Net deep convolutional neural network, which is robust to small errors in the annotation according to my experience. 
To see how exactly we have done it, [you can check out the dataset which we have used here.](https://www.kaggle.com/tivadardanka/plant-segmentation) (I'll get back to you soon on how to overlay the masks on top of the images so you can see what each region contains.)

For the training, you should use the `patched_images` folder. (Although the `converted` will work as well, but according to our experience, it is better to use the patched ones.)

Please let me know if there are any results or other issues! We would love to use your feedback to improve the tool!

Cheers,
Tivadar

**Comment by amoudomola** [comment]
Thank you so much for your prompt reply and valuable advice! 

Best regards,
Goh
