### ISSUE TITLE
Using measure.py from another python file with subprocess.run("python measure.py...")

### ISSUE THREAD

**Issue by darvida** [biomag-lab/hypocotyl-UNet#10]
Hello, i'm using a tkinter file to run a the measure.py file on a selected image, but when i'm using the "subprocess" package with the function subprocess.run("python measure.py --images_path=C:/....") the tkinter window crashes, do you know what it might be ? 
I can see the following output in the Python Console window:
Loading dataset...
Dataset loaded
Loading model...
Model loaded
Measuring images...
Measuring IMG_0917.png

But i wont get any output in the result folder

**Comment by cosmic-cortex** [comment]
Unfortunately, I have zero experience with tkinter, so I don't know what might be the problem.
