### ISSUE TITLE
Error when trying to run in google colab. Name with space in it. 

### ISSUE THREAD

**Issue by darvida** [biomag-lab/hypocotyl-UNet#13]
The train.py does not work when using google Colab as the name of the google drive folder is in the following way "/content/gdrive/My Drive/training_unet/model/" with the folder "My Drive" having a space in the name the file train.py thinks that it is a command. Do you know here i can change it so that only "=" would count as an input argument to the specific(ArgumentParser).

Thanks for the help :)

**Comment by cosmic-cortex** [comment]
Just for reference, I'll answer :) In these cases, putting the string between quotes should work. That is,
```
--model "/content/gdrive/My Drive/training_unet/model/"
```
